let score =72;
if(score>=90){
    console.log("Grade: A");
}
else if(score>=75){
    console.log("Grade: B");
}else{
    console.log("Grade: C");    
}

let day=3;
switch(day){
    case 1:
        console.log("Monday");
        break;
    case 2:
        console.log("Tuesday");
        break;
    case 3:
        console.log("Wednesday");
        break;
    case 4:
        console.log("Thursday");
        break;
    case 5:
        console.log("Friday");
        break;
    default:
        console.log("Weekend");
}